stages:
  prepare_model:
    cmd: python src/stage_01_prepare.py --config configs/config.yaml --params params.yaml
    deps:
      - src/stage_01_prepare.py
      - src/utils/common.py
      - configs/config.yaml 
      - params.yaml 
    outs:
      - artifacts/model/
  featurization:
    cmd: python src/stage_02_featurization.py --config configs/config.yaml --params params.yaml
    deps:
      - configs/config.yaml 
      - params.yaml
      - src/stage_02_featurization.py
  training:
    cmd: python src/stage_03_train.py --config configs/config.yaml --params params.yaml
    deps:
      - configs/config.yaml
      - params.yaml
      - src/stage_03_train.py
      - src/stage_02_featurization.py
      - src/stage_01_prepare.py
      - artifacts/model/
      - src/utils/metrics.py
      - src/utils/common.py
    

