stages:
  prepare_model:
    cmd: python src/stage_01_prepare.py --config configs/config.yaml --params params.yaml
    deps:
      - src/stage_01_prepare.py
      - src/utils/common.py
      - configs/config.yaml 
      - params.yaml 
      - requirements.txt
    outs:
      - artifacts/model/
  featurization:
    cmd: python src/stage_02_featurization.py --config configs/config.yaml --params params.yaml
    deps:
      - configs/config.yaml 
      - params.yaml
      - src/stage_02_featurization.py
      - requirements.txt
  training:
    cmd: python src/stage_03_train.py --config configs/config.yaml --params params.yaml
    deps:
      - configs/config.yaml 
      - params.yaml
      - requirements.txt
      - src/stage_01_prepare.py
      - src/stage_02_featurization.py
      - src/stage_03_train.py
      - src/utils/metrics.py
      - src/utils/common.py
    plots:
      - plots/itr_loss.json:
          cache:  false
          x: Iteration
          y: Iteration Loss
      - plots/avg_batch_loss.json:
          cache:  false
          x:  Epoch
          y:  Batch Loss
      - plots/validation_metrics.json:
          cache:  false
          x:  Epoch
          y:  F1-Score
    outs:
      - artifacts/checkpoints/
  evaluate:
    cmd: python src/stage_04_evaluate.py --config configs/config.yaml --params params.yaml
    deps:
      - configs/config.yaml 
      - params.yaml
      - requirements.txt
      - src/stage_01_prepare.py
      - src/stage_02_featurization.py
      - src/stage_03_train.py
      - src/stage_04_evaluate.py
      - src/utils/metrics.py
      - src/utils/common.py
      - artifacts/model/
      - artifacts/checkpoints/
    metrics:
      - metrics/test_f1.json:
          cache: False
      - metrics/test_score.json:
          cache: False
  run_plots_command:
    cmd:  dvc plots diff