artifacts:
  artifacts_dir: artifacts
  model:
    model_dir: model
    model_name: resnet18
    pretrained: False
    repo: pytorch_vision_v0.10.0
    model_weights:  checkpoints
  data_source:
    data_dir: cat-dog
    train_folder: training_set
    test_folder: test_set

checkpoint:
  checkpoint_name: resnet18_batch-size-5_epochs-1_learning_rate-0.001.pth

plots:
  plots_dir: 'plots'
  itr_loss: 'itr_loss.json'
  avg_batch_loss: 'avg_batch_loss.json'
  validation_metrics: 'validation_metrics.json'

metrics:
  metrics_dir: metrics
  test_f1: 'test_f1.json'
  test_score: 'test_score.json'