artifacts:
  artifacts_dir: artifacts
  model:
    model_dir: model
    model_name: resnet18
    pretrained: False
  data_source:
    data_dir: cat-dog
    train_folder: training_set
    test_folder: test_set